(defpackage #:fx-quant-kit
  (:use #:cl)
  (:export
   ;; Conditions and validation
   #:quantitative-error
   #:invalid-argument
   #:invalid-argument-name
   #:invalid-argument-value
   #:invalid-shape
   #:invalid-shape-expected
   #:invalid-shape-actual
   #:insufficient-data
   #:insufficient-data-required
   #:insufficient-data-actual
   #:numerical-error
   #:numerical-error-operation
   #:domain-error
   #:domain-error-operation
   #:domain-error-value
   #:ensure-real
   #:ensure-finite
   #:ensure-positive
   #:ensure-non-negative
   #:ensure-probability
   #:approx=

   ;; Macro and continuation DSL
   #:define-value-record
   #:define-cps-wrapper
   #:define-cps-wrappers
   #:mean/k
   #:weighted-mean/k
   #:variance/k
   #:standard-deviation/k
   #:covariance/k
   #:correlation/k
   #:sum-of-squares/k
   #:simple-returns/k
   #:log-returns/k
   #:cumulative-return/k
   #:quantile/k
   #:median/k
   #:normal-pdf/k
   #:normal-cdf/k
   #:inverse-normal-cdf/k
   #:skewness/k
   #:excess-kurtosis/k
   #:sharpe-ratio/k
   #:sortino-ratio/k
   #:beta/k
   #:tracking-error/k
   #:information-ratio/k
   #:covariance-matrix/k
   #:correlation-matrix/k
   #:fx-forward-rate/k
   #:fx-forward-points/k
   #:fx-cross-rate/k
   #:fx-pip-distance/k
   #:fx-pnl/k
   #:pip-value/k
   #:sma/k
   #:ema/k
   #:wilder-average/k
   #:rsi/k
   #:macd/k
   #:bollinger-bands/k
   #:true-range/k
   #:atr/k
   #:hurst-exponent/k
   #:garch11-variance/k
   #:garch11-forecast/k
   #:realized-volatility/k
   #:black-scholes-price/k
   #:black-scholes-greeks/k
   #:implied-volatility/k
   #:rng-uniform/k
   #:rng-normal/k
   #:simulate-geometric-brownian-motion/k
   #:simulate-ornstein-uhlenbeck/k
   #:monte-carlo-estimate/k
   #:historical-var/k
   #:historical-expected-shortfall/k
   #:parametric-var/k
   #:parametric-expected-shortfall/k
   #:kelly-fraction/k
   #:volatility-target-position/k
   #:drawdown-series/k
   #:max-drawdown/k
   #:portfolio-variance/k
   #:portfolio-volatility/k
   #:portfolio-risk-contributions/k
   #:stress-loss/k
   #:risk-decision/k

   ;; Statistics and distributions
   #:mean
   #:weighted-mean
   #:variance
   #:standard-deviation
   #:covariance
   #:correlation
   #:sum-of-squares
   #:simple-returns
   #:log-returns
   #:cumulative-return
   #:quantile
   #:median
   #:normal-pdf
   #:normal-cdf
   #:inverse-normal-cdf
   #:skewness
   #:excess-kurtosis
   #:sharpe-ratio
   #:sortino-ratio
   #:beta
   #:tracking-error
   #:information-ratio
   #:covariance-matrix
   #:correlation-matrix

   ;; Market data values
   #:market-quote
   #:market-quote-p
   #:make-market-quote
   #:market-quote-timestamp
   #:market-quote-bid
   #:market-quote-ask
   #:market-quote-mid
   #:market-quote-spread
   #:tick-data
   #:tick-data-p
   #:make-tick-data
   #:tick-data-timestamp
   #:tick-data-bid
   #:tick-data-ask
   #:tick-data-bid-size
   #:tick-data-ask-size
   #:tick-data-mid
   #:tick-data-spread
   #:tick-data-total-size
   #:tick-data-imbalance
   #:ohlcv-bar
   #:ohlcv-bar-p
   #:make-ohlcv-bar
   #:ohlcv-bar-timestamp
   #:ohlcv-bar-open
   #:ohlcv-bar-high
   #:ohlcv-bar-low
   #:ohlcv-bar-close
   #:ohlcv-bar-volume
   #:timestamp->instant
   #:instant->timestamp
   #:timestamp->iso8601
   #:iso8601->timestamp

   ;; FX conventions
   #:currency
   #:currency-p
   #:make-currency
   #:currency-code
   #:currency-pair
   #:currency-pair-p
   #:make-currency-pair
   #:currency-pair-base
   #:currency-pair-quote
   #:currency-pair-pip-size
   #:fx-forward-rate
   #:fx-forward-points
   #:fx-cross-rate
   #:fx-pip-distance
   #:fx-pnl
   #:pip-value
   #:market-quote->json
   #:json->market-quote
   #:tick-data->json
   #:json->tick-data
   #:ohlcv-bar->json
   #:json->ohlcv-bar
   #:currency->json
   #:json->currency
   #:currency-pair->json
   #:json->currency-pair

   ;; Indicators and volatility
   #:sma
   #:ema
   #:wilder-average
   #:rsi
   #:macd-result
   #:macd-result-p
   #:make-macd-result
   #:macd-result-line
   #:macd-result-signal
   #:macd-result-histogram
   #:macd
   #:bollinger-result
   #:bollinger-result-p
   #:make-bollinger-result
   #:bollinger-result-middle
   #:bollinger-result-upper
   #:bollinger-result-lower
   #:bollinger-bands
   #:true-range
   #:atr
   #:hurst-exponent
   #:garch11-variance
   #:garch11-forecast
   #:realized-volatility

   ;; Option pricing and stochastic processes
   #:black-scholes-price
   #:option-contract
   #:option-contract-p
   #:make-option-contract
   #:option-contract-option-type
   #:option-contract-strike
   #:option-contract-time-to-expiry
   #:option-contract-payoff
   #:option-contract-price
   #:option-contract-greeks
   #:discount-factor
   #:present-value
   #:forward-price
   #:black-scholes-greeks
   #:black-scholes-greeks-p
   #:make-black-scholes-greeks
   #:greeks-price
   #:greeks-delta
   #:greeks-gamma
   #:greeks-vega
   #:greeks-theta
   #:greeks-rho
   #:implied-volatility
   #:simulation-rng
   #:simulation-rng-p
   #:make-simulation-rng
   #:simulation-rng-seed
   #:rng-uniform
   #:rng-normal
   #:simulate-geometric-brownian-motion
   #:simulate-ornstein-uhlenbeck
   #:monte-carlo-estimate

   ;; Risk
   #:historical-var
   #:historical-expected-shortfall
   #:parametric-var
   #:parametric-expected-shortfall
   #:kelly-fraction
   #:volatility-target-position
   #:drawdown-series
   #:max-drawdown
   #:portfolio-variance
   #:portfolio-volatility
   #:portfolio-risk-contributions
   #:stress-loss
   #:risk-decision-state
   #:risk-decision-state-p
   #:make-risk-decision-state
   #:risk-decision-state-blackout-p
   #:risk-decision-state-drawdown
   #:risk-decision-state-max-drawdown
   #:risk-decision-state-volatility
   #:risk-decision-state-max-volatility
   #:risk-decision-result
   #:risk-decision-result-p
   #:make-risk-decision-result
   #:risk-decision-result-action
   #:risk-decision-result-reason
   #:risk-decision-result-state
   #:risk-decision))
