(in-package #:fx-quant-kit)

(defun implied-volatility (target-price spot strike time-to-expiry
                           risk-free-rate
                           &key (dividend-yield 0d0) (option-type :call)
                             (lower-bound 1d-8) (upper-bound 8d0)
                             (tolerance 1d-10) (max-iterations 200))
  "Solve for the Black-Scholes volatility using a bracketed bisection.

The target must lie within the prices generated by LOWER-BOUND and
UPPER-BOUND.  A bracketed method is slower than Newton iteration but remains
well behaved near low-vega regions and has no hidden global state."
  (let ((target-price (ensure-non-negative target-price :target-price)))
    (multiple-value-bind (spot strike time-to-expiry ignored-volatility
                          risk-free-rate dividend-yield option-type)
        (%black-scholes-inputs spot strike time-to-expiry 1d0
                               risk-free-rate dividend-yield option-type)
      (declare (ignore ignored-volatility))
      (let* ((lower-bound (ensure-positive lower-bound :lower-bound))
             (upper-bound (ensure-positive upper-bound :upper-bound))
             (tolerance (ensure-positive tolerance :tolerance))
             (max-iterations
               (progn
                 (unless (and (integerp max-iterations)
                              (plusp max-iterations))
                   (error 'invalid-argument
                          :name :max-iterations
                          :value max-iterations))
                 max-iterations)))
        (when (>= lower-bound upper-bound)
          (error 'invalid-argument
                 :name :volatility-bracket
                 :value (list lower-bound upper-bound)))
        (let ((lower-price (black-scholes-price
                            spot strike time-to-expiry lower-bound
                            risk-free-rate
                            :dividend-yield dividend-yield
                            :option-type option-type))
              (upper-price (black-scholes-price
                            spot strike time-to-expiry upper-bound
                            risk-free-rate
                            :dividend-yield dividend-yield
                            :option-type option-type)))
          (unless (<= lower-price target-price upper-price)
            (error 'domain-error
                   :operation 'implied-volatility
                   :value target-price))
          (loop with low = lower-bound
                with high = upper-bound
                for iteration from 1 to max-iterations
                for midpoint = (/ (+ low high) 2d0)
                for price = (black-scholes-price
                             spot strike time-to-expiry midpoint
                             risk-free-rate
                             :dividend-yield dividend-yield
                             :option-type option-type)
                when (< (abs (- price target-price)) tolerance)
                  do (return midpoint)
                do (if (< price target-price)
                       (setf low midpoint)
                       (setf high midpoint))
                finally (error 'numerical-error
                               :operation 'implied-volatility)))))))
